# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '2.2.401'
  - script: dotnet build ./SimplCommerce.sln
    displayName: 'dotnet build'
  - script: ./run-tests.sh
    displayName: 'run tests'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/*.trx'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx' 

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '2.2.401'
  - script: dotnet build ./SimplCommerce.sln
    displayName: 'dotnet build'
  - task: PowerShell@2
    inputs:
      filePath: .\run-tests.ps1
    displayName: 'run tests'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/*.trx'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx' 
      - task: SonarQubePrepare@5
        inputs:
          SonarQube: 'SonarQube COnnection'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'testsonar'
          cliProjectName: 'Test Sonar'
          cliSources: '.'
          - task: SonarQubeAnalyze@5
            inputs:
              jdkversion: 'JAVA_HOME_11_X64'
      - task: dependency-check-build-task@6
        inputs:
          projectName: 'Test Sonar'
          scanPath: '/'
          format: 'HTML, JSON, JUNIT'
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'